services:
  db:
    image: postgres:14
    container_name: smartfarm-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./SmartFarmBackEnd
    container_name: smartfarm-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    restart: always

  frontend:
    build:
      context: ./SmartFarmFrontEnd
      args:
      # build 시 REACT_APP_BACKEND_URL 을 Dockerfile 에 전달
       REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
    container_name: smartfarm-frontend
    env_file:
        - .env        # 런타임에도 ENV로 주고 싶다면
    ports:
        - "3000:80"   # nginx 기본 80 → 호스트 3000
    depends_on:
        - backend
volumes:
  pgdata: