
services:
  db:
    image: postgres:14
    container_name: smartfarm-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./SmartFarmBackEnd
    container_name: smartfarm-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./uploads:/uploads
    depends_on:
      - db

  frontend:
    build:
      context: ./SmartFarmFrontEnd
      args:
        REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
    container_name: smartfarm-frontend
    env_file:
      - .env
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata: