version: '3.8'
services:
  db:
    image: postgres:14
    container_name: smartfarm-db
    environment:
      POSTGRES_DB: smartfarm
      POSTGRES_USER: son
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./SmartFarmBackEnd
    container_name: smartfarm-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: default
    restart: always
    
  frontend:
    build: ./SmartFarmFrontEnd
    container_name: smartfarm-frontend
    ports:
      - "3000:80"  # nginx 포트가 80이므로 외부에 3000으로 노출
    depends_on:
      - backend

volumes:
  pgdata: