spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  address: 0.0.0.0
  port: 8080
  servlet:
    session:
      cookie:
        same-site: Lax
        secure: false

app:
  upload-dir: ${APP_UPLOAD_DIR:/app/uploads}
  dev:
    allow-upload-without-session: false

mqtt:
  broker: ${MQTT_BROKER}
  client-id: ${MQTT_CLIENT_ID}
  topic-sub: ${MQTT_TOPIC_SUB}
  topic-pub: ${MQTT_TOPIC_PUB}