spring:
  datasource:
    url: jdbc:postgresql://db:5432/smartfarm
    username: son
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create # or create, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
